[workspace]
resolver = "3"

members = [
    "rust/transaction_signer",
    "rust/transaction_db",
    "rust/transaction_sender",
]

[workspace.dependencies]
transaction_db = { path = "./rust/transaction_db" }
